import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import "jspdf-autotable";

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session?.user) return new NextResponse("Unauthorized", { status: 401 });

  try {
    const { id } = await params;
    const appointment = await prisma.appointment.findUnique({
      where: { id },
      include: {
        client: { include: { clientProfile: true } },
        practitioner: { include: { practitionerProfile: true } },
        service: true,
      },
    });

    if (!appointment) return new NextResponse("Appointment not found", { status: 404 });

    const doc = new jsPDF() as any;
    const client = appointment.client;
    const practitioner = appointment.practitioner;

    // Header - Oku Clinic Brand
    doc.setFontSize(22);
    doc.setTextColor(26, 24, 23); // Oku Dark
    doc.text("OKU CLINIC", 20, 20);
    doc.setFontSize(10);
    doc.text("CLINICAL SUPERBILL", 20, 28);

    // Practitioner Info
    doc.setFontSize(12);
    doc.text(`${practitioner.name}`, 140, 20);
    doc.setFontSize(10);
    doc.text(`NPI: ${practitioner.practitionerProfile?.npiNumber || "N/A"}`, 140, 26);
    doc.text(`License: ${practitioner.practitionerProfile?.licenseNumber || "N/A"}`, 140, 31);

    // Client Info
    doc.setFontSize(14);
    doc.text("Patient Information", 20, 50);
    doc.setFontSize(10);
    doc.text(`Name: ${client.name}`, 20, 58);
    doc.text(`DOB: ${client.clientProfile?.dateOfBirth?.toLocaleDateString() || "N/A"}`, 20, 63);
    doc.text(`Address: ${client.location || "On File"}`, 20, 68);

    // Table of Services
    doc.autoTable({
      startY: 80,
      head: [['Date', 'Service Code (CPT)', 'Description', 'Duration', 'Fee']],
      body: [
        [
          new Date(appointment.startTime).toLocaleDateString(),
          '90837', // Default psychotherapy code
          appointment.service.name,
          `${appointment.service.duration} mins`,
          `$${appointment.service.price}`
        ]
      ],
      theme: 'grid',
      headStyles: { fillColor: [42, 38, 36], textColor: [255, 255, 255] },
    });

    // Totals
    const finalY = (doc as any).lastAutoTable.finalY || 100;
    doc.setFontSize(12);
    doc.text(`Total Amount Paid: $${appointment.service.price}`, 140, finalY + 20);
    doc.setFontSize(10);
    doc.text("Status: PAID", 140, finalY + 28);

    // Footer
    doc.setFontSize(8);
    doc.text("This document is generated by Oku Clinic as a record for insurance reimbursement purposes.", 20, 280);

    const pdfOutput = doc.output('arraybuffer');
    
    // Mark as generated in DB
    await prisma.appointment.update({
        where: { id: appointment.id },
        data: { superbillGenerated: true }
    });

    return new Response(pdfOutput, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="Oku_Superbill_${appointment.id}.pdf"`,
      },
    });

  } catch (error) {
    console.error("[SUPERBILL_GENERATION_ERROR]", error);
    return new NextResponse("Internal Error", { status: 500 });
  }
}
