// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/about-us" | "/admin/dashboard" | "/admin/financials" | "/admin/practitioners" | "/admin/sessions" | "/admin/therapists" | "/admin/users" | "/assessments" | "/assessments/[slug]" | "/assessments/anxiety" | "/auth/login" | "/auth/practitioner-signup" | "/auth/signin" | "/auth/signup" | "/blog" | "/blog/[slug]" | "/checkout/[sessionId]" | "/checkout/[sessionId]/success" | "/consent" | "/contact" | "/dashboard" | "/dashboard/client" | "/dashboard/client/adhd" | "/dashboard/client/book" | "/dashboard/client/book/[id]/superbill" | "/dashboard/client/book/new/[therapistId]" | "/dashboard/client/book/new/[therapistId]/trial" | "/dashboard/client/clinical" | "/dashboard/client/intake" | "/dashboard/client/messages" | "/dashboard/client/mood" | "/dashboard/client/profile" | "/dashboard/client/referrals" | "/dashboard/client/sessions" | "/dashboard/client/support" | "/dashboard/client/therapists" | "/dashboard/client/vault" | "/dashboard/profile" | "/dashboard/therapist" | "/emergency" | "/faq" | "/practitioner/appointments" | "/practitioner/assessments" | "/practitioner/assessments/new" | "/practitioner/availability" | "/practitioner/billing" | "/practitioner/blogs" | "/practitioner/clients" | "/practitioner/clients/[id]" | "/practitioner/dashboard" | "/practitioner/intelligence" | "/practitioner/messages" | "/practitioner/profile" | "/practitioner/schedule" | "/practitioner/sessions/[id]/notes" | "/practitioner/support" | "/privacy" | "/services" | "/session/[id]" | "/terms" | "/therapists"
type AppRouteHandlerRoutes = "/api/activities/track" | "/api/admin/oci" | "/api/admin/users/create" | "/api/admin/users/reset-password" | "/api/ai/chat" | "/api/assessments" | "/api/auth/2fa/setup" | "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/availability/update" | "/api/book/trial" | "/api/checkout" | "/api/clinical/analytics" | "/api/clinical/insurance" | "/api/clinical/reminders/process" | "/api/clinical/scribe" | "/api/clinical/superbill/[id]" | "/api/clinical/transcribe" | "/api/clinical/transcript/process" | "/api/clinical/transcript/sync" | "/api/documents" | "/api/messages" | "/api/mood" | "/api/notes/create" | "/api/payments/razorpay/create-order" | "/api/payments/stripe/create-intent" | "/api/payments/webhook-simulator" | "/api/practitioner/appointments" | "/api/practitioner/assessments" | "/api/practitioner/assessments/assign" | "/api/practitioner/profile" | "/api/practitioner/treatment-plans" | "/api/sessions/[id]" | "/api/sessions/[id]/no-show" | "/api/sessions/create" | "/api/tasks" | "/api/therapists/[id]" | "/api/therapists/match" | "/api/user/change-password" | "/api/user/consent" | "/api/user/intake" | "/api/user/profile" | "/api/video/token" | "/api/webhook/razorpay" | "/api/webhook/stripe"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/auth" | "/dashboard" | "/practitioner"
type RedirectRoutes = "/people"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/about-us": {}
  "/admin": {}
  "/admin/dashboard": {}
  "/admin/financials": {}
  "/admin/practitioners": {}
  "/admin/sessions": {}
  "/admin/therapists": {}
  "/admin/users": {}
  "/api/activities/track": {}
  "/api/admin/oci": {}
  "/api/admin/users/create": {}
  "/api/admin/users/reset-password": {}
  "/api/ai/chat": {}
  "/api/assessments": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/2fa/setup": {}
  "/api/auth/register": {}
  "/api/availability/update": {}
  "/api/book/trial": {}
  "/api/checkout": {}
  "/api/clinical/analytics": {}
  "/api/clinical/insurance": {}
  "/api/clinical/reminders/process": {}
  "/api/clinical/scribe": {}
  "/api/clinical/superbill/[id]": { "id": string; }
  "/api/clinical/transcribe": {}
  "/api/clinical/transcript/process": {}
  "/api/clinical/transcript/sync": {}
  "/api/documents": {}
  "/api/messages": {}
  "/api/mood": {}
  "/api/notes/create": {}
  "/api/payments/razorpay/create-order": {}
  "/api/payments/stripe/create-intent": {}
  "/api/payments/webhook-simulator": {}
  "/api/practitioner/appointments": {}
  "/api/practitioner/assessments": {}
  "/api/practitioner/assessments/assign": {}
  "/api/practitioner/profile": {}
  "/api/practitioner/treatment-plans": {}
  "/api/sessions/[id]": { "id": string; }
  "/api/sessions/[id]/no-show": { "id": string; }
  "/api/sessions/create": {}
  "/api/tasks": {}
  "/api/therapists/[id]": { "id": string; }
  "/api/therapists/match": {}
  "/api/user/change-password": {}
  "/api/user/consent": {}
  "/api/user/intake": {}
  "/api/user/profile": {}
  "/api/video/token": {}
  "/api/webhook/razorpay": {}
  "/api/webhook/stripe": {}
  "/assessments": {}
  "/assessments/[slug]": { "slug": string; }
  "/assessments/anxiety": {}
  "/auth": {}
  "/auth/login": {}
  "/auth/practitioner-signup": {}
  "/auth/signin": {}
  "/auth/signup": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/checkout/[sessionId]": { "sessionId": string; }
  "/checkout/[sessionId]/success": { "sessionId": string; }
  "/consent": {}
  "/contact": {}
  "/dashboard": {}
  "/dashboard/client": {}
  "/dashboard/client/adhd": {}
  "/dashboard/client/book": {}
  "/dashboard/client/book/[id]/superbill": { "id": string; }
  "/dashboard/client/book/new/[therapistId]": { "therapistId": string; }
  "/dashboard/client/book/new/[therapistId]/trial": { "therapistId": string; }
  "/dashboard/client/clinical": {}
  "/dashboard/client/intake": {}
  "/dashboard/client/messages": {}
  "/dashboard/client/mood": {}
  "/dashboard/client/profile": {}
  "/dashboard/client/referrals": {}
  "/dashboard/client/sessions": {}
  "/dashboard/client/support": {}
  "/dashboard/client/therapists": {}
  "/dashboard/client/vault": {}
  "/dashboard/profile": {}
  "/dashboard/therapist": {}
  "/emergency": {}
  "/faq": {}
  "/people": {}
  "/practitioner": {}
  "/practitioner/appointments": {}
  "/practitioner/assessments": {}
  "/practitioner/assessments/new": {}
  "/practitioner/availability": {}
  "/practitioner/billing": {}
  "/practitioner/blogs": {}
  "/practitioner/clients": {}
  "/practitioner/clients/[id]": { "id": string; }
  "/practitioner/dashboard": {}
  "/practitioner/intelligence": {}
  "/practitioner/messages": {}
  "/practitioner/profile": {}
  "/practitioner/schedule": {}
  "/practitioner/sessions/[id]/notes": { "id": string; }
  "/practitioner/support": {}
  "/privacy": {}
  "/services": {}
  "/session/[id]": { "id": string; }
  "/terms": {}
  "/therapists": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/auth": never
  "/dashboard": never
  "/practitioner": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
