// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(marketing)/about-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about-us">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/about-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/assessments/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessments/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/assessments/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/assessments/anxiety/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessments/anxiety">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/assessments/anxiety/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessments">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/emergency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/emergency">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/emergency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/financials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/financials">> = Specific
  const handler = {} as typeof import("../../app/admin/financials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/practitioners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/practitioners">> = Specific
  const handler = {} as typeof import("../../app/admin/practitioners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sessions">> = Specific
  const handler = {} as typeof import("../../app/admin/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/therapists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/therapists">> = Specific
  const handler = {} as typeof import("../../app/admin/therapists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/practitioner-signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/practitioner-signup">> = Specific
  const handler = {} as typeof import("../../app/auth/practitioner-signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/[sessionId]">> = Specific
  const handler = {} as typeof import("../../app/checkout/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/[sessionId]/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/[sessionId]/success">> = Specific
  const handler = {} as typeof import("../../app/checkout/[sessionId]/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/consent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consent">> = Specific
  const handler = {} as typeof import("../../app/consent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/adhd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/adhd">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/adhd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/book/[id]/superbill/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/book/[id]/superbill">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/book/[id]/superbill/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/book/new/[therapistId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/book/new/[therapistId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/book/new/[therapistId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/book/new/[therapistId]/trial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/book/new/[therapistId]/trial">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/book/new/[therapistId]/trial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/book">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/clinical/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/clinical">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/clinical/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/intake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/intake">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/intake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/messages">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/mood/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/mood">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/mood/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/profile">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/referrals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/referrals">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/referrals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/sessions">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/support">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/therapists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/therapists">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/therapists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/client/vault/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client/vault">> = Specific
  const handler = {} as typeof import("../../app/dashboard/client/vault/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/therapist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/therapist">> = Specific
  const handler = {} as typeof import("../../app/dashboard/therapist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/appointments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/appointments">> = Specific
  const handler = {} as typeof import("../../app/practitioner/appointments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/assessments/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/assessments/new">> = Specific
  const handler = {} as typeof import("../../app/practitioner/assessments/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/assessments">> = Specific
  const handler = {} as typeof import("../../app/practitioner/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/availability">> = Specific
  const handler = {} as typeof import("../../app/practitioner/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/billing">> = Specific
  const handler = {} as typeof import("../../app/practitioner/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/blogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/blogs">> = Specific
  const handler = {} as typeof import("../../app/practitioner/blogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/clients/[id]">> = Specific
  const handler = {} as typeof import("../../app/practitioner/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/clients">> = Specific
  const handler = {} as typeof import("../../app/practitioner/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/dashboard">> = Specific
  const handler = {} as typeof import("../../app/practitioner/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/intelligence">> = Specific
  const handler = {} as typeof import("../../app/practitioner/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/messages">> = Specific
  const handler = {} as typeof import("../../app/practitioner/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/profile">> = Specific
  const handler = {} as typeof import("../../app/practitioner/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/schedule">> = Specific
  const handler = {} as typeof import("../../app/practitioner/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/sessions/[id]/notes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/sessions/[id]/notes">> = Specific
  const handler = {} as typeof import("../../app/practitioner/sessions/[id]/notes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practitioner/support">> = Specific
  const handler = {} as typeof import("../../app/practitioner/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/session/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/session/[id]">> = Specific
  const handler = {} as typeof import("../../app/session/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/therapists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/therapists">> = Specific
  const handler = {} as typeof import("../../app/therapists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/activities/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activities/track">> = Specific
  const handler = {} as typeof import("../../app/api/activities/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/oci/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/oci">> = Specific
  const handler = {} as typeof import("../../app/api/admin/oci/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/create">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/reset-password">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/chat">> = Specific
  const handler = {} as typeof import("../../app/api/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assessments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments">> = Specific
  const handler = {} as typeof import("../../app/api/assessments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/2fa/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/2fa/setup">> = Specific
  const handler = {} as typeof import("../../app/api/auth/2fa/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/availability/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/availability/update">> = Specific
  const handler = {} as typeof import("../../app/api/availability/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/book/trial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/book/trial">> = Specific
  const handler = {} as typeof import("../../app/api/book/trial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clinical/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/clinical/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clinical/insurance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical/insurance">> = Specific
  const handler = {} as typeof import("../../app/api/clinical/insurance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clinical/reminders/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical/reminders/process">> = Specific
  const handler = {} as typeof import("../../app/api/clinical/reminders/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clinical/scribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical/scribe">> = Specific
  const handler = {} as typeof import("../../app/api/clinical/scribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clinical/superbill/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical/superbill/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/clinical/superbill/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clinical/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical/transcribe">> = Specific
  const handler = {} as typeof import("../../app/api/clinical/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clinical/transcript/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical/transcript/process">> = Specific
  const handler = {} as typeof import("../../app/api/clinical/transcript/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clinical/transcript/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical/transcript/sync">> = Specific
  const handler = {} as typeof import("../../app/api/clinical/transcript/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents">> = Specific
  const handler = {} as typeof import("../../app/api/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mood/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mood">> = Specific
  const handler = {} as typeof import("../../app/api/mood/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notes/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/create">> = Specific
  const handler = {} as typeof import("../../app/api/notes/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payments/razorpay/create-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/razorpay/create-order">> = Specific
  const handler = {} as typeof import("../../app/api/payments/razorpay/create-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payments/stripe/create-intent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/stripe/create-intent">> = Specific
  const handler = {} as typeof import("../../app/api/payments/stripe/create-intent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payments/webhook-simulator/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/webhook-simulator">> = Specific
  const handler = {} as typeof import("../../app/api/payments/webhook-simulator/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/practitioner/appointments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/practitioner/appointments">> = Specific
  const handler = {} as typeof import("../../app/api/practitioner/appointments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/practitioner/assessments/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/practitioner/assessments/assign">> = Specific
  const handler = {} as typeof import("../../app/api/practitioner/assessments/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/practitioner/assessments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/practitioner/assessments">> = Specific
  const handler = {} as typeof import("../../app/api/practitioner/assessments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/practitioner/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/practitioner/profile">> = Specific
  const handler = {} as typeof import("../../app/api/practitioner/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/practitioner/treatment-plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/practitioner/treatment-plans">> = Specific
  const handler = {} as typeof import("../../app/api/practitioner/treatment-plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[id]/no-show/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[id]/no-show">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[id]/no-show/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/create">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/therapists/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/therapists/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/therapists/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/therapists/match/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/therapists/match">> = Specific
  const handler = {} as typeof import("../../app/api/therapists/match/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/change-password">> = Specific
  const handler = {} as typeof import("../../app/api/user/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/consent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/consent">> = Specific
  const handler = {} as typeof import("../../app/api/user/consent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/intake/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/intake">> = Specific
  const handler = {} as typeof import("../../app/api/user/intake/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/video/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/video/token">> = Specific
  const handler = {} as typeof import("../../app/api/video/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook/razorpay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/razorpay">> = Specific
  const handler = {} as typeof import("../../app/api/webhook/razorpay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/stripe">> = Specific
  const handler = {} as typeof import("../../app/api/webhook/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(marketing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practitioner/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/practitioner">> = Specific
  const handler = {} as typeof import("../../app/practitioner/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
